class dnsmasq {
	package { "dnsmasq":
		ensure => present,
	}

	$dnsmasq_conf = "
resolv-file=/etc/resolv-dnsmasq.conf
interface=eth1
no-dhcp-interface=eth0
no-dhcp-interface=eth1
no-hosts
addn-hosts=/etc/hosts.splunk
"

	file { "/etc/dnsmasq.conf":
		ensure  => file,
		content => $dnsmasq_conf,
		require => Package["dnsmasq"],
	}

	file { "/etc/resolv-dnsmasq.conf":
		ensure => file,
		source => "/etc/resolv.conf",
		require => Package["dnsmasq"],
	}

	file { "/etc/resolv.conf":
		ensure => file,
		content => "
# generated by puppet
nameserver 127.0.0.1
",
		require => Service["dnsmasq"]
	}

	$splunk_hosts = "
192.168.50.2	search-head.splunk
192.168.50.3	master.splunk
192.168.50.11	peer1.splunk
192.168.50.12	peer2.splunk
192.168.50.13	peer3.splunk
192.168.50.11	forward.splunk
192.168.50.12	forward.splunk
192.168.50.13	forward.splunk
"

	file { "/etc/hosts.splunk":
		ensure  => file,
		content => $splunk_hosts,
		notify  => Service["dnsmasq"],
	}

	service {"dnsmasq":
		ensure  => "running",
		require => [
			Package["dnsmasq"],
			File["/etc/dnsmasq.conf"],
		],
	}
}