# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

splunk_rpm="splunk-6.1.3-220630-linux-2.6-x86_64.rpm"
sos_tgz="sos-splunk-on-splunk_32.tgz"
sideview_utils_tgz="sideview-utils-lgpl_135.tgz"
splunkonnix_tgz="splunk-app-for-unix-and-linux_501.tgz"
splunktanix_tgz="splunk-add-on-for-unix-and-linux_503.tgz"
host_name="splunk"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/centos-6.5-64-puppet"

  config.vm.host_name = host_name
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024","--name",host_name]
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
	puppet.module_path = "puppet/modules"
	puppet.facter = {
		"splunk_rpm" => splunk_rpm,
		"sos_tgz" => sos_tgz,
		"sideview_utils_tgz" => sideview_utils_tgz,
		"splunkonnix_tgz" => splunkonnix_tgz,
		"splunktanix_tgz" => splunktanix_tgz
	}
  end
end
